### ISSUE TITLE
Need forum_main

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#112]
**Description**
We need to implement a forum_main.html to handle posts and threads, just like a real forum

**Details**
The current forum posts section just lists the posts in an order.  We actually need to load a page that contains links to the forum post by the title name.  

**Parent Issue**
#84

**Additional Details**
![image](https://user-images.githubusercontent.com/58710710/180678622-491f53f8-5080-45f8-b37b-260ffeeda93e.png)

**Comment by stuart909** [comment]
The example I provided doesn't have to be exact, but we should load a view similar to that, just more forumy

**Comment by stuart909** [comment]
git fetch origin
git checkout 112-need-forum_main

**Comment by stuart909** [comment]
- to access forum_main, the user should be authenticated.  I want the forum link to be visible on our main nav bar, but we can error handle the lack of authentication and forward them to the login screen.
- forum sections / folders / threads should be rendered first
- posts should be rendered in their thread with proper indentation
- posts with no threads should be rendered last.
- dont forget to use the CSS property for the slider to allow scrolling in your div.  Tobupengin.com has a working example.

**Comment by jmm28** [comment]
If I'm understanding correctly, would the approach be to create 2 for-loops (one nested inside of the other), with the outer loop representing the folders and the inner loop representing that folder's posts?

**Comment by stuart909** [comment]
I suppose you could do it that way in the jinja template, makes sense

**Comment by jmm28** [comment]
It's my understanding that Andy already has the code that covers the main forum page in his forums_main.html file (https://github.com/Pengin-Open-Source/pengin-pie/tree/85-create-forum-post-form-andy), so I've added him as an assignee here.

**Comment by jmm28** [comment]
![Screen Shot 2022-07-31 at 6 10 18 PM](https://user-images.githubusercontent.com/65846682/182049079-2d292989-bd76-4088-80fb-42c912214959.png)
This is what I have so far. I restructured things a bit on both the front and back end (e.g. making a Forum Thread model), and there are definitely things I need to iron out (esp. when it comes to routing and storing/displaying the posts, since there's a bit of an issue with how the URL is created and the fact that the post titles don't link back to their actual post content).
