### ISSUE TITLE
Dynamo DB Documentation

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#24]
This is an issue tracker for useful DynamoDB information:

- [Official AWS DynamoDB docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html)
- [AWS API documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.API.html)
- [Project example 1](https://www.bacancytechnology.com/blog/aws-dynamodb-with-flask-apis-and-boto3)
- [Project example 2](https://medium.com/featurepreneur/crud-operations-on-dynamodb-with-flask-apis-916f6cae992)
- [Dynamo-Crud Pypi.org](https://pypi.org/project/dynamo-crud/)
- [Dynamo-Crud source](https://github.com/Pengin-Open-Source/dynamo-crud)

**Comment by imamyy** [comment]
Hello guys, I just want to check up on everyone. How is everyone doing? Do you have any trouble or difficulty finishing these issues that assigned to you last week? Since I don't see any updates neither from you guys nor on GitHub issues. If you are busy or too bored not knowing what to do or have any difficulties, please speak up to me, Zini, or Stuart so that we know how the team is doing. Thank you
