### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#37]
We would like to have a profile page where the logged in user may actually review the profile data and make changes via web form.  I will leave the front-end task open for interpretation based on your own skill.

Possible ways to do this:
Simply make a form that loads the user data from database in text inputs that can be changed.  Add a submit button that pushes the changes to that user's account.  This is probably easiest but not desirable.

Make a profile page that displays the user form data in a non-editable form.  Use JQuery or javascript to add a modify button that transforms the read only form to a write-able form.  Submit button to make changes, same as first example.
 
Keep the profile page a simple readable page with a web link to load in a write-able profile page dynamically in the same position.  This is probably easier than option 2, but slightly more involved than option 1, as you need to make an additional jinja template and handle the routes.

**Comment by bmeissn2** [comment]
Hey how's everything going Jasmine?  Whats the status of your tasks?  Can you update me when you have a moment

**Comment by jmm28** [comment]
> How is it going Jasmine? Do you need help with this?

Right now I have the white box on the right changing to be about profile info (instead of the Important Information links) on the profile page, the edit profile page, and the edit password page. I've created a separate .html file for the edit password page. I don't think things are functional yet (routes.py mainly has placeholder functions for these), but I think navigation should be working between everything.

**Comment by jmm28** [comment]
> 

It isn't much, but I'll push what I have.

**Comment by stuart909** [comment]
adding the team to this issue.  I also put this issue into the admin view milestone.  We need to be aware that someone logged in with admin should have a different profile view.
