### ISSUE TITLE
fix personal info link menu

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#73]
personal info link needs to load this profile page:
![image](https://user-images.githubusercontent.com/58710710/179154608-90916a1a-7f26-472a-8546-2a236ac88a21.png)

**Comment by stuart909** [comment]
git fetch origin
git checkout 73-fix-personal-info-link-menu

**Comment by DanielRiquelmeReb** [comment]
I changed the list attribute to buttons/hyperlink in order to give it an interactive appearance (right_window\profile_info.html). It highlights the button where the cursor is hovering. I also added the href of the personal info button pointing to "/profile" .I didn't want to create a pull request until it was checked before by Jasmine. I pushed the changes to [73-fix-personal-info-link-menu-Daniel](https://github.com/Pengin-Open-Source/pengin-pie/tree/73-fix-personal-info-link-menu-Daniel) branch.

**Comment by jmm28** [comment]
I think it looks fine!

**Comment by stuart909** [comment]
> I changed the list attribute to buttons/hyperlink in order to give it an interactive appearance (right_window\profile_info.html). It highlights the button where the cursor is hovering. I also added the href of the personal info button pointing to "/profile" .I didn't want to create a pull request until it was checked before by Jasmine. I pushed the changes to [73-fix-personal-info-link-menu-Daniel](https://github.com/Pengin-Open-Source/pengin-pie/tree/73-fix-personal-info-link-menu-Daniel) branch.

Did we ever get a pull request on this?  The deadline is Friday and this has been silent for almost a week.

**Comment by bmeissn2** [comment]
Jasmine, can you please elaborate on what looks fine?  Did he do a pull request?

**Comment by jmm28** [comment]
> Jasmine, can you please elaborate on what looks fine? Did he do a pull request?

I had checked out the branch and I didn't find problems with the buttons/hyperlinks.

**Comment by stuart909** [comment]
Yes.  I pulled it down and verified the branch manually.  The point being, when we get our code to a place where it can be reviewed, a pull request should be created and we should get it peer reviewed so we can move the process along.
